# fly.toml app configuration file generated for wild-butterfly-1373 on 2023-10-31T09:14:09+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wild-butterfly-1373"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
